### ISSUE TITLE
Need a maximum filename length

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lv_fs_if#1]
At the moment, there is no way to know how long the filename retrieved by `fs_dir_read` in `lv_fs_pc.c` is going to be. It would be better to set a maximum length IMO.

**Comment by embeddedt** [comment]
Never mind. After looking again, I found it at the top of the header file. Still, I think this would be good to mention in the function comment.

**Comment by kisvegabor** [comment]
> After looking again, I found it at the top of the header file.

Where did you find it? I don't know about define like this.

**Comment by embeddedt** [comment]
It's in `lv_misc/lv_fs.h`: https://github.com/littlevgl/lvgl/blob/27db08eb23e579010217c8b878c5ef6a739580fc/src/lv_misc/lv_fs.h#L31

**Comment by kisvegabor** [comment]
I see. I've just checked and it's not used at all. So we can move it and `MAX_PATH_LENGTH` here.

**Comment by embeddedt** [comment]
> So we can move it and `MAX_PATH_LENGTH` here.

It doesn't really matter, but in terms of organization, I think it makes more sense to leave those defines over there, since they pertain to the filesystem module.

**Comment by kisvegabor** [comment]
> It doesn't really matter, but in terms of organization, I think it makes more sense to leave those defines over there, since they pertain to the filesystem module.

I've also considered it.
But actually `lv_fs.c` operates only with pointers and don't allocate buffers for filenames and paths. These buffers are used on the caller side (e.g. when you call `lv_fs_read_dir(&read_dir, fn)`) or in the driver, if some operations need to be done.
In addition, different drivers might require different buffer sizes.
In light of that, I vote for placing it to `lv_fs_if`. What do you think?

**Comment by embeddedt** [comment]
@kisvegabor Fair enough; we can leave it in this repository.

**Comment by kisvegabor** [comment]
The most flexible solution could be to defines to the FATFS and PCFS drivers too which can be overwritten by the user. However, I'm not sure it's worth this abstraction. IMO two common defines with `ifndef` guards in `lv_fs_if.h` should be enough. What do you think?

--- 

BTW, you mentioned that you'd like to use `lv_fs_if` for the file browser app. Could you share your idea about it in https://github.com/littlevgl/lv_examples/issues/31 or in a new issue?
As it's a complex thing it should be useful to discuss it first.

**Comment by embeddedt** [comment]
> IMO two common defines with ifndef guards in lv_fs_if.h should be enough. What do you think?

That should be fine.

> Could you share your idea about it in littlevgl/lv_examples#31 or in a new issue?

I will comment there.
