### ISSUE TITLE
Error when compiling new-api branch

### ISSUE THREAD

**Issue by elgerg** [lvgl/lv_fs_if#11]
Hi,

When compiling this for posix i get the following errors:

gcc -I"/home/alex/Workspace/pc_simulator_sdl_eclipse" -O0 -g3 -Wall -c -fmessage-length=0 -Wall -Wmaybe-uninitialized -MMD -MP -MF"lv_fs_if/lv_fs_posix.d" -MT"lv_fs_if/lv_fs_posix.o" -o "lv_fs_if/lv_fs_posix.o" "../lv_fs_if/lv_fs_posix.c"
../lv_fs_if/lv_fs_posix.c:55:77: error: unknown type name ‘lv_fs_whence_t’; did you mean ‘lv_fs_file_t’?
 static lv_fs_res_t fs_seek (lv_fs_drv_t * drv, void * file_p, uint32_t pos, lv_fs_whence_t whence);
                                                                             ^~~~~~~~~~~~~~
                                                                             lv_fs_file_t
../lv_fs_if/lv_fs_posix.c: In function ‘lv_fs_if_posix_init’:
../lv_fs_if/lv_fs_posix.c:93:20: warning: assignment to ‘lv_fs_res_t (*)(struct _lv_fs_drv_t *, void *, const char *, lv_fs_mode_t)’ {aka ‘unsigned char (*)(struct _lv_fs_drv_t *, void *, const char *, unsigned char)’} from incompatible pointer type ‘void * (*)(lv_fs_drv_t *, const char *, lv_fs_mode_t)’ {aka ‘void * (*)(struct _lv_fs_drv_t *, const char *, unsigned char)’} [-Wincompatible-pointer-types]
     fs_drv.open_cb = fs_open;
                    ^
../lv_fs_if/lv_fs_posix.c:97:22: error: ‘fs_seek’ undeclared (first use in this function); did you mean ‘fseek’?
     fs_drv.seek_cb = fs_seek;

![image](https://user-images.githubusercontent.com/24628571/103482096-9d294600-4dd6-11eb-9515-2c3edafd4ecb.png)

Do you know what i am doing wrong?

Thanks

**Comment by elgerg** [comment]
If i change from lv_fs_whence_t to;

static lv_fs_res_t fs_seek (lv_fs_drv_t * drv, void * file_p, uint32_t pos, int whence);

it seems to compile. I must be missing something?

**Comment by kisvegabor** [comment]
Have you used lvgl with `feat/new-fs-api` branch too?

**Comment by kisvegabor** [comment]
I've just updated `feat/new-fs-api` from the latest `master`.

**Comment by elgerg** [comment]
I'll give it a go. Thanks

**Comment by elgerg** [comment]
Something seemed to work.

I think I had separately added the lib where I didnt need to.

Thanks!
