### ISSUE TITLE
How to go back to the previous directory?

### ISSUE THREAD

**Issue by Miguel0101** [lvgl/lv_fs_if#13]
How to go back to the previous directory?

**Comment by kisvegabor** [comment]
How did you enter into a directory? :smile: There is no such a function in LVGL as `cd directory` on Linux.

**Comment by Miguel0101** [comment]
No, How to go back to the previous directory with `lv_fs_if`?

**Comment by embeddedt** [comment]
On Linux, using `..` in the path should work.

**Comment by Miguel0101** [comment]
I'm using ESP32.

**Comment by kisvegabor** [comment]
I don't understand. As there is no function to enter into the directory how do you want to go back?

What do you want to achieve in more detail?

**Comment by Miguel0101** [comment]
Tried to use `lv_fs_dir_open("..")` but to no avail.

**Comment by Miguel0101** [comment]
> What do you want to achieve in more detail?

I want to know how to get back to the previous directory using `lv_fs_if`.

**Comment by kisvegabor** [comment]
ESP should support `..` but you haven't set the driver letter in `lv_fs_dir_open`.

I suggest reading this section of the docs: https://docs.lvgl.io/master/overview/file-system.html

After that simply try to open and read a file first to see the drivers are working.

**Comment by embeddedt** [comment]
So far you have simply repeated yourself. :slightly_smiling_face: 

As @kisvegabor mentioned, I'm not aware of any way to change directories in LVGL, thus it's unclear to me how you are in any child directory to begin with.

**Comment by Miguel0101** [comment]
> ESP should support `..` but you haven't set the driver letter in `lv_fs_dir_open`.
> 
> I suggest reading this section of the docs: https://docs.lvgl.io/master/overview/file-system.html
> 
> After that simply try to open and read a file first to see the drivers are working.

Okay, I set the driver letter, so it's lv_fs_open_dir(&dir, "S:/folder/.."), but it didn't work.

**Comment by Miguel0101** [comment]
> So far you have simply repeated yourself. 🙂
> 
> As @kisvegabor mentioned, I'm not aware of any way to change directories in LVGL, thus it's unclear to me how you are in any child directory to begin with.

I'm trying to go back to the previous directory, eg `lv_fs_dir_open(&dir, "S:/folder")` the current directory is "S:/folder", using `lv_fs_dir_open(&dir, "S:/folder/..")` the previous directory is " S:/".

**Comment by kisvegabor** [comment]
Why don't you simply write `lv_fs_dir_open(&dir, "S:")`?

**Comment by Miguel0101** [comment]
> Why don't you simply write `lv_fs_dir_open(&dir, "S:")`?

Because it's an object selected by an lv_list.

**Comment by embeddedt** [comment]
The issue is that continually appending the selected item wouldn't work too well anyways, as you would require more and more memory as the user browses through folders.

The correct approach is usually to store the current path in a buffer, and when you detect `..` being pressed, remove the last path chunk from the buffer.

I have a [very old gist](https://gist.github.com/embeddedt/be0adf541e65a2fbbf3c5e2e4efd85e1) which implements a file browser in this manner. It was last updated for LVGL 6, but you can get the general idea. Just look at the spots where `current_dir` is referenced.

**Comment by Miguel0101** [comment]
> The issue is that continually appending the selected item wouldn't work too well anyways, as you would require more and more memory as the user browses through folders.
> 
> The correct approach is usually to store the current path in a buffer, and when you detect `..` being pressed, remove the last path chunk from the buffer.
> 
> I have a [very old gist](https://gist.github.com/embeddedt/be0adf541e65a2fbbf3c5e2e4efd85e1) which implements a file browser in this manner. It was last updated for LVGL 6, but you can get the general idea. Just look at the spots where `current_dir` is referenced.

Thanks @embeddedt.
