### ISSUE TITLE
lib/lv_fs_if-master/lv_fs_fatfs.c:207:5: error: unknown type name 'DIR'

### ISSUE THREAD

**Issue by mojtabakh13** [lvgl/lv_fs_if#18]
Hi
First of all thanks for the awesome LVGL.
But I have a problem in the file system interface
here's the issue:

lib/lv_fs_if-master/lv_fs_fatfs.c: In function 'fs_dir_open':
lib/lv_fs_if-master/lv_fs_fatfs.c:207:5: error: unknown type name 'DIR'
     DIR * d = lv_mem_alloc(sizeof(DIR));
     ^
lib/lv_fs_if-master/lv_fs_fatfs.c:207:35: error: 'DIR' undeclared (first use in this function)
     DIR * d = lv_mem_alloc(sizeof(DIR));

I used the new API and the latest lvgl master and add requirements in README.md.
Is there anything I should do?

**Comment by kisvegabor** [comment]
You need to add the FatFS library to you project too.

**Comment by FrancisGut** [comment]
Hello, First of all, Thanks for LVGL library! .I have used the LVGL with Arduino for ESP32 and I try to use file system interface for SD card. But I have the same issue than mojtabakh13. I explain you the steps I did:
- I download the folder lv_fs_if-master and unzip it to src folder of lvgl renaming to  lv_fs_if
- I add the line #include "src/lv_fs_if/lv_fs_if.h" in lvgl.h
- I add in lv_conf.h
/*File system interface*/
#define LV_USE_FS_IF 1
#if LV_USE_FS_IF
#define LV_FS_IF_FATFS    'S'
#define LV_FS_IF_PC       '\0'
#define LV_FS_IF_POSIX    '\0'
#endif  /*LV_USE_FS_IF*/
- I add #include "ff.h" in my main project.

Are these steps corrects?
Thanks for your support.

**Comment by kisvegabor** [comment]
> I add #include "ff.h" in my main project.

Have you also added FatFS library?

`DIR` seems valid. See http://elm-chan.org/fsw/ff/doc/opendir.html

**Comment by yangislet** [comment]
i got same trouble. the IDE can't find the "lv_fs_whence_t" and "DIR" ,they are undefined, I can't find the header file

**Comment by yangislet** [comment]
the latest Fatfs lib  take the place of  "Dir" by the "FF_DIR", and add the code in the file of  "lv_fs_fatfs.c" `typedef uint32_t lv_fs_whence_t;
enum
{
    LV_FS_SEEK_SET = 0x00,
    LV_FS_SEEK_CUR = 0x01,
    LV_FS_SEEK_END = 0x02,
};`

**Comment by kisvegabor** [comment]
Glad to hear that you have found the problem.

Could you send a PR to update our FS interface? If yo, please send it for the lvgl repo.
