### ISSUE TITLE
Arduino Esp32  lv_fs_if-new-api   lvgl at version 8.1.1-dev  err

### ISSUE THREAD

**Issue by fsyzty** [lvgl/lv_fs_if#19]
#### err log:
Alternatives for lvgl/lvgl.h: []
ResolveLibrary(lvgl/lvgl.h)In file included from C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:9:

  -> candidates: []C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_if.h:19:10: fatal error: lvgl/lvgl.h: No such file or directory

 #include <lvgl/lvgl.h>
          ^~~~~~~~~~~~~
compilation terminated.

#### charge lv_fs_if.h.   #include <lvgl.h>

err log:
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c: In function 'lv_fs_if_fatfs_init':
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:78:11: error: 'lv_fs_drv_t' {aka 'struct _lv_fs_drv_t'} has no member named 'free_space_cb'
     fs_drv.free_space_cb = fs_free;
           ^
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:79:12: error: 'lv_fs_drv_t' {aka 'struct _lv_fs_drv_t'} has no member named 'size_cb'; did you mean 'write_cb'?
     fs_drv.size_cb = fs_size;
            ^~~~~~~
            write_cb
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:80:12: error: 'lv_fs_drv_t' {aka 'struct _lv_fs_drv_t'} has no member named 'remove_cb'; did you mean 'ready_cb'?
     fs_drv.remove_cb = fs_remove;
            ^~~~~~~~~
            ready_cb
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:81:12: error: 'lv_fs_drv_t' {aka 'struct _lv_fs_drv_t'} has no member named 'rename_cb'; did you mean 'ready_cb'?
     fs_drv.rename_cb = fs_rename;
            ^~~~~~~~~
            ready_cb
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:82:12: error: 'lv_fs_drv_t' {aka 'struct _lv_fs_drv_t'} has no member named 'trunc_cb'; did you mean 'open_cb'?
     fs_drv.trunc_cb = fs_trunc;
            ^~~~~~~~
            open_cb
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c: In function 'fs_dir_open':
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:292:5: error: unknown type name 'DIR'; did you mean 'DDR'?
     DIR * d = lv_mem_alloc(sizeof(DIR));
     ^~~
     DDR
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:292:35: error: 'DIR' undeclared (first use in this function); did you mean 'DDR'?
     DIR * d = lv_mem_alloc(sizeof(DIR));
                                   ^~~
                                   DDR
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:292:35: note: each undeclared identifier is reported only once for each function it appears in
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:295:29: warning: passing argument 1 of 'f_opendir' from incompatible pointer type [-Wincompatible-pointer-types]
     FRESULT res = f_opendir(d, path);
                             ^
In file included from C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:13:
C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1/tools/sdk/esp32/include/fatfs/src/ff.h:290:28: note: expected 'FF_DIR *' {aka 'struct <anonymous> *'} but argument is of type 'int *'
 FRESULT f_opendir (FF_DIR* dp, const TCHAR* path);      /* Open a directory */
                    ~~~~~~~~^~
C:\Users\User\Documents\Arduino\libraries\lvgl\src\lv_fs_if\lv_fs_fatfs.c:296:14: error: expected expression before '=' token
     if(res !== FR_OK) {
              ^
Using library lvgl at version 8.1.1-dev in folder: C:\Users\User\Documents\Arduino\libraries\lvgl 
Using library TFT_eSPI at version 2.3.70 in folder: C:\Users\User\Documents\Arduino\libraries\TFT_eSPI 
Using library SPI at version 2.0.0 in folder: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1\libraries\SPI 
Using library FS at version 2.0.0 in folder: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1\libraries\FS 
Using library SPIFFS at version 2.0.0 in folder: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1\libraries\SPIFFS 
Using library FFat at version 2.0.0 in folder: C:\Users\User\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.1\libraries\FFat 
Using library lv_examples at version 8.1.1-dev in folder: C:\Users\User\Documents\Arduino\libraries\lv_examples 
exit status 1
Error compiling for board ESP32 Dev Module.

**Comment by fsyzty** [comment]
Can use LITTLEFS?
https://github.com/espressif/arduino-esp32/blob/master/libraries/FFat/examples/FFat_Test/FFat_Test.ino
https://github.com/espressif/arduino-esp32/blob/master/libraries/SPIFFS/examples/SPIFFS_Test/SPIFFS_Test.ino
https://github.com/espressif/arduino-esp32/blob/master/libraries/LittleFS/examples/LITTLEFS_test/LITTLEFS_test.ino

**Comment by kisvegabor** [comment]
You should use the file system interface from lvgl directly. 

I don't know about LittleFS. If it has a custom API (as FatFS) then it requires its own interface in LVGL.
