### ISSUE TITLE
Missing a few features

### ISSUE THREAD

**Issue by embeddedt** [lvgl/lv_fs_if#2]
I'm working on the file browser, but I've hit some roadblocks with the API.

* There is no way to tell whether a directory entry is a file or a directory.
* At the moment, there is no limit set on the length of a path. Currently I've assumed it's the same as the file length (which isn't really correct).

**Comment by kisvegabor** [comment]
> There is no way to tell whether a directory entry is a file or a directory.

It's really not documented yet. The directory names should begin with `/`.

> At the moment, there is no limit set on the length of a path. Currently I've assumed it's the same as the file length (which isn't really correct).

True. There should be a config option for it in and the file name length too.

**Comment by embeddedt** [comment]
Just realized I never replied to this. Sorry.

> It's really not documented yet. The directory names should begin with `/`.

That works, although it's a little unintuitive from a user's perspective IMO.

> There should be a config option for it in [`lv_conf.h`] and the file name length too.

I can add that soon.

**Comment by kisvegabor** [comment]
> Just realized I never replied to this. Sorry.

No problem!

> That works, although it's a little unintuitive from a user's perspective IMO.

It should be mentioned that the file system module itself doesn't rely on it. User can mark the dictionaries as he wants. However, I felt it quite intuitive :)   Midnight commander also uses it:
![image](https://user-images.githubusercontent.com/7599318/61514959-97cd1580-aa01-11e9-8d52-07c5a1ca7a56.png)

>> There should be a config option for it in [lv_conf.h] and the file name length too.

> I can add that soon.

Awesome!

**Comment by embeddedt** [comment]
Not stale.
