### ISSUE TITLE
stm32h747 lvgl v8.2 error fatfs

### ISSUE THREAD

**Issue by Yurii202** [lvgl/lv_fs_if#20]
Hello. When lv_fs_drv_register(&fs_drv); HardFault_Handler crashes. What am I doing wrong?

**Comment by kisvegabor** [comment]
Does it can right on he function call?

**Comment by Yurii202** [comment]
Inside a function when executing lv_tlsf.c  static size_t block_size(const block_header_t * block).

**Comment by Yurii202** [comment]
HardFault_Handler() at stm32h7xx_it.c:89 0x80062fa	
<signal handler called>() at 0xffffffe9	
block_size() at lv_tlsf.c:384 0x80540d0	
block_locate_free() at lv_tlsf.c:775 0x8054980	
lv_tlsf_malloc() at lv_tlsf.c:1 102 0x8054c3c	
lv_mem_alloc() at lv_mem.c:132 0x80514ee	
_lv_ll_ins_head() at lv_ll.c:71 0x8050d64	
lv_fs_drv_register() at lv_fs.c:401 0x8050c2a	
lv_fs_if_fatfs_init() at lv_fs_fatfs.c:100 0x801a330	
lv_fs_if_init() at lv_fs_if.c:55 0x801a660
