### ISSUE TITLE
filesystem not work

### ISSUE THREAD

**Issue by banshanju** [lvgl/lv_fs_if#3]
I've already transplanted the driver of FATFS, when i use the code like this:
```c
 lv_obj_t *img_bin_t = lv_img_create(parent, NULL); /*Crate an image object*/
 lv_img_set_src(img_bin_t, "0:wallpaper.bin");  /*Set the created file as image (a red rose)*/
 lv_obj_set_pos(img_bin_t, 400, 100);      /*Set the positions*/
 lv_obj_set_drag(img_bin_t, true);
```

it print:  **Image draw cannot open the image resource**

but when i use the code like this:
```c
FRESULT res = f_open(&file_p,"0:wallpaper.bin",FA_READ);
 if(res==FR_OK)printf("\r\nread ok");
 else printf("\r\nread err");
 f_close(&file_p);`
```

it print:   **read ok**

so i guess there is something wrong in the lvgl  filesystem

**Comment by kisvegabor** [comment]
In `lv_img_set_src(img_bin_t, "0:wallpaper.bin"); ` instead of `0:` you should write the letter of the drive. E.g. `lv_img_set_src(img_bin_t, "S:wallpaper.bin"); `

If you are using this repo the letter is set by `LV_FS_IF_FATFS`. See the [Usage](https://github.com/littlevgl/lv_fs_if#usage) section in the README or can read more about the FIle system module in the [documentation](https://docs.littlevgl.com/en/html/overview/file-system.html).

**Comment by banshanju** [comment]
in fatfs ,the sdcard letter is 0, so i set the letter as 0. But LV_FS_IF_FATFS is not 0.

 ` fs_drv.file_size =  sizeof(file_t);

    fs_drv.letter = 0;
    fs_drv.open_cb = fs_open;
    fs_drv.close_cb = fs_close;`

I add these codes in lv_conf.h:
`#define LV_USE_FS_IF	1
#if LV_USE_FS_IF
#  define LV_FS_IF_FATFS    's'
#  define LV_FS_IF_PC       '\0'
#endif  /*LV_USE_FS_IF*/`

FATFS driver:
`#define ATA			    0    // SD Card
#define SPI_FLASH		1    // spi flash
#define USB         2    // USB Disk(USB Host)`

`DSTATUS disk_initialize (
	BYTE pdrv				/* Physical drive nmuber to identify the drive */
)
{
		DSTATUS status = STA_NOINIT;
	switch (pdrv) {
		case ATA:	/* SD CARD */
			#if FATFS_USE_SDIO == 1
				status = TM_FATFS_SD_SDIO_disk_initialize();	/* SDIO communication */
			#endif
			break;`

then the screen can display a rectangle with label "No data" in it, the rectangle size is equal to the picture

**Comment by embeddedt** [comment]
I think you misunderstood what @kisvegabor is suggesting. 

You don't need to register a driver yourself. It will be registered automatically when you call `lv_fs_if_init` using the letter you provide in `lv_conf.h`.

Then you should reference the file using that letter (`s:file.png`).

**Comment by kisvegabor** [comment]
Besides, you should use an upper case letter: `'S'`

Your fatfs functions will receive a path like `"folder/file.txt"`. You have to format it as you need, e.g. add `"0:"` in front of the path.

The drive letter is used only to decide which driver to call.

Note:
I could use FATFS without `"0:"`. 
https://github.com/littlevgl/lv_fs_if/blob/70b9a31f6152946b934fcbd37b6de899a22f0070/lv_fs_fatfs.c#L126

**Comment by embeddedt** [comment]
> I could use FATFS without "0:"

I think it is smart enough to handle it in the case of one drive.

> Besides, you should use an upper case letter

Is there a limitation regarding that, or is it just a convention? From reading the code it didn't appear that it mattered.

**Comment by kisvegabor** [comment]
> I think it is smart enough to handle it in the case of one drive.

In the first example where he mounts only one drive, he also leaves to `"0:"` mark. 
http://elm-chan.org/fsw/ff/doc/open.html

> Is there a limitation regarding that, or is it just a convention? From reading the code it didn't appear that it mattered.

It was limitation earlier in `lv_img_src_get_type` to decide the passed variable is a string, a symbol or an `lv_img_dsc_t` variable but now lowercase letters should work too. I've forgotten that it was already improved.

So it's rather like a convention.

**Comment by banshanju** [comment]
Thanks for embeddedt and kisvegabor. With your help, i found out it was my fault.

I use lv_fs to create a txt file,and write some words in it.  It's OK.
This time ,i use the letter 'S' to define LV_FS_IF_FATFS , and use the path "S:textfile.txt".

But it still can't display a image ,the screen  display a rectangle with label "No data" in it.
The file "blue_rose_16.bin" is selected from lv_examples , and i set the LV_COLOR_DEPTH equal 16.
Is there anything else that needs to be changed?

**Comment by kisvegabor** [comment]
> But it still can't display a image ,the screen display a rectangle with label "No data" in it.
The file "blue_rose_16.bin" is selected from lv_examples , and i set the LV_COLOR_DEPTH equal 16.
Is there anything else that needs to be changed?

You can enable logging in lv_conf.h to see where the issue occurs or debug from `lv_img_design()` (in lv_img.c)

**Comment by banshanju** [comment]
I found that version 6.1 was released. And i update the version from 6.0 to 6.1,the problem has been solved.
I'm so happy.

**Comment by kisvegabor** [comment]
v6.1 is still in the development stage. We are working on it in the `dev-6.1` branch. Where did you see that it is already released? Maybe we weren't clear enough somewhere.

Anyway, you can use `dev-6.1` without any problem. It will be backward compatible with v6.0.

**Comment by banshanju** [comment]
I described some mistakes. I download the source codes from the dev-6.1 branch.

**Comment by kisvegabor** [comment]
I see, that's fine.
However, I'd be curious about what was the issue in v6.0.

Do you have an example to show the issue in the simulator?

**Comment by banshanju** [comment]
Yes，i test the lv_examples/lv_tutorial/6_images in the simulator just now, it also can't display the images.

**Comment by kisvegabor** [comment]
There was a bug related to this it was fixed a few days ago. Please update lvgl from the master and try again.
