### ISSUE TITLE
Support for ESP32 file system

### ISSUE THREAD

**Issue by prathameshjakka** [lvgl/lv_fs_if#6]
Support for accessing files using SD card for ESP32

**Comment by kisvegabor** [comment]
I moved this issue to `lv_fs_if` repo.

It'd be great to support ESP32 FS too.

Are you interested in contributing to this improvement?

**Comment by prathameshjakka** [comment]
yes, I am interested in contributing to this improvement, I just need some help as I'm not so good with C, it's my first time using something than an Arduino library

**Comment by kisvegabor** [comment]
> yes, I am interested in contributing to this improvement,

Great! :slightly_smiling_face: 

Actually all you need to do is creating some wrappers around the File IO function of ESP.

I haven't immersed in ESP File systems deeply but at first look it seems they use POSIX API. So [PC FS example](https://github.com/lvgl/lv_fs_if/blob/master/lv_fs_pc.c) os LVGL can be a good starting point.

**Comment by prathameshjakka** [comment]
I have implemented a file browser using Arduino SD library and still haven't implemented a feature to access directories, it can only access the root folder for now. Work in progress

![IMG_20200725_165053](https://user-images.githubusercontent.com/9351264/88455988-b7f6a680-ce97-11ea-95ce-abd69b93fbe4.jpg)

**Comment by kisvegabor** [comment]
Have you used ESP file manager functions or LVGL's FS API?

I've added a POSIX file system module to this repo. It seems ESP uses POSIX API so I hope it simply work with ESP32 too. It's in the `new-api` branch. See the README about how to use it.

It's not complete yet but base file management (open, read, write, seek, close) should work. Can you try it on ESP?
E.g.
```c
lv_fs_file_t * f;
f = lv_fs_open("X/path/to/file", LV_FS_MODE_RD);
char buf[32];
lv_fs_read(f, buf, 32, NULL);
lv_fs_close(f);
```

**Comment by prathameshjakka** [comment]
hey sorry for the late reply but I'm having a hard time understanding how to implement this feature, I'm using lv_arduino and have connected the SD card in SPI on the same SPI as the display.In Arduino SD card pins and CS pins can be set, how do we initialize SD card in this example?

**Comment by kisvegabor** [comment]
Unfortunately, I don't know much about these details of ESP32 and Arduino. And it seems unrelated to LVGL. 

LVGL's filesystem is built on top of a working file system handler. That is when you can open without LVGL some wrapper can be added to add a drive to LVGL.

**Comment by prathameshjakka** [comment]
okay, I got your point what are some things that I should learn to understand this topic better and contribute to this issue?

**Comment by kisvegabor** [comment]
Does the file system of ESP (without LVGL) already work?

If not take a look its documentation https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/storage/index.html

**Comment by lewisxhe** [comment]
esp32 uses posix api, which is fully compatible.

**Comment by kisvegabor** [comment]
@lewisxhe 
Thanks for the confirmation. In this case, the `new-api` branch should work.

**Comment by kisvegabor** [comment]
I tested that with the C IO API (e.g. `fopen`) and ESP32 were also working with that. An example path: `P/spiffs/file.txt`.

So I close this as this repo already supports ESP32.

**Comment by beckmx** [comment]
@kisvegabor based on your comment, the path when using SPIFFS should be like that?
`P/spiffs/my_file.txt`
And the changes in the lv_conf.h should be?

```
#define LV_USE_FS_IF	1
#if LV_USE_FS_IF
#  define LV_FS_IF_POSIX    '\0'
#endif  /*LV_USE_FS_IF*/
```

**Comment by embeddedt** [comment]
@beckmx I believe you need a colon between the drive letter (P) and the `/`; I think the lack of it is just a typo.

The `lv_conf.h` changes look correct.

**Comment by beckmx** [comment]
@kisvegabor I got this error, I think in the new **_new-api_** branch this type is missing _lv_fs_whence_t_

`lib/lv_fs_if/lv_fs_posix.c:55:77: error: unknown type name 'lv_fs_whence_t'; did you mean 'lv_fs_file_t'?`

**Comment by lewisxhe** [comment]
I have tested it a long time ago, if you need to refer to it, please see this 

examples:

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/979828ef8d7fd072b321dfb6c90ece38d93b1e25/examples/LVGL/ChargingAnimation/ChargingAnimation.ino#L71

src:

https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/979828ef8d7fd072b321dfb6c90ece38d93b1e25/src/libraries/lv_fs_if/lv_fs_pc.c#L27


https://github.com/Xinyuan-LilyGO/TTGO_TWatch_Library/blob/979828ef8d7fd072b321dfb6c90ece38d93b1e25/src/TTGO.h#L746

,
Hope to help you

**Comment by beckmx** [comment]
@lewisxhe thanx for you input, really helped me understand how everything was loaded, unfortuantely I couldnt make it work :( even with your code I get this error:

```
OPEN /fs/0.png FAILED!!!!
/fs/0.png
Failed to open /fs/0.png
```

Seems more an access problem with the mkspiffs or how the data is store ( i used the esp32 data upload in arduino) 

I also wrote my own fs driver but even the posix and the pc drivers have problems, and by problems I mean, the **_fopen_** method sees the file, but the **_fread_** method, looks that it doesnt actually read :(
