### ISSUE TITLE
error when compile new-api branch

### ISSUE THREAD

**Issue by stetzanton** [lvgl/lv_fs_if#7]
Have error when compile new-api branch (lv_fs_if) with LVGL new-fs-api branch.
http://joxi.ru/EA4WQDIok9oD2b

**Comment by kisvegabor** [comment]
Hi,

FATFS wasn't updated to new api yet. I added the required changes but couldn't test it now.

**Comment by stetzanton** [comment]
I updated to new version and find some errors.
1 - lost ; in http://joxi.ru/krDJLnhK9oxK2p
2 - fs_open and fs_seek have conflicting types.
all in lv_fs_fatfs.c

**Comment by kisvegabor** [comment]
All three should be fixed.

**Comment by stetzanton** [comment]
Thanks, errors is gone.
I have next question:

```
  lv_fs_file_t f;
  lv_fs_res_t res;
  res = fs_open(&f, "S:/hello.txt", LV_FS_MODE_RD);
  if(res != LV_FS_RES_OK) printf("error open hello.txt\n");
  lv_fs_close(&f);
```
After build i receive "undefined reference to fs_open"
What am I doing wrong?

**Comment by kisvegabor** [comment]
Do you see it in `lv_misc/lv_fs.c`? ANd have you enabled `LV_USE_FILESYSTEM`?

Note that in the new API it should be used like this:
```c
lv_fs_file_t * f = fs_open("S:/hello.txt", LV_FS_MODE_RD);
if(f == NULL) ...error...
```

**Comment by stetzanton** [comment]
I change code, but problem is remained.
warning: implicit declaration of function 'fs_open'
error: undefined reference to `fs_open'
LV_USE_FILESYSTEM and LV_USE_FS_IF are enabled in lv_conf.h

i'm call in main.c:
  lv_init();
  lv_fs_if_init();
  lv_fs_file_t * f = fs_open("S:/hello.txt", LV_FS_MODE_RD);

include lv_fs_if.h

Maybe i wrong, but fs_open() is a static function and resides in lv_fs_fatfs.c How we can access it directly?

**Comment by kisvegabor** [comment]
You should use `lv_fs_open` (lv_ prefixed).

I also mistyped it in my previous comment...

**Comment by stetzanton** [comment]
with lv_fs_open i receive NULL in this part of code http://joxi.ru/ZrJJQ7hwypY6rj 
lv_fs.c file
I try to open simple txt file from SD card

**Comment by kisvegabor** [comment]
Have you mounted and initialized FATFS?
Does it work without LVGL?

**Comment by stetzanton** [comment]
Yes, all work ok with master branch of lvgl without lv_fs_if
Images in .bin format from sdcard loaded and displayed correctly.

But bin, gif files don't loaded with new-api lvgl and lv_fs_if
images from flash in .c format loaded correctly
Maybe I missed something
i try to load  test.txt in main.c,  but also fail

**Comment by kisvegabor** [comment]
Ah, I've found something. Just pushed this fix: https://github.com/lvgl/lv_fs_if/commit/8b1d3d5fa79ae37a0b8c5d7432fe492bdbad345c
