### ISSUE TITLE
Arduino interface ESP32

### ISSUE THREAD

**Issue by daowa89** [lvgl/lv_fs_if#8]
I am working on an interface between lvgl and arduino (ESP32). Unfortunately I have difficulty with the implementation and need some support.

`typedef  File file_t;`
`fs_drv.file_size = sizeof(file_t);`

![image](https://user-images.githubusercontent.com/76402915/102722297-8c6dd000-4300-11eb-8f3d-0f201dd24710.png)
![image](https://user-images.githubusercontent.com/76402915/102722306-97c0fb80-4300-11eb-8723-c1fbfbabd33e.png)

I am not sure, if i am returning the pointer to the file instance the correct way. Within the function fs_open I get the correct size of the file. Outside the function, I always get the wrong size. So I assume, that the pointer to the file class is not delivered correctly.

![image](https://user-images.githubusercontent.com/76402915/102722286-7bbd5a00-4300-11eb-91ee-e632556bb094.png)

If I can finish the interface, I will provide the code with pleasure.

**Comment by kisvegabor** [comment]
Hi,

Please try with the `new-api` branch. `LV_FS_IF_PC` should work out of the box.

**Comment by daowa89** [comment]
Unfortunately not that easy, because I am using a modified library for the spi communication to the sd-card.
I don't want to throw away this stuff, because I am sure, that it's only a detail, why my code is not working.

With calling the method SD.open() i get a new instance of the class File. I only need to know, how to store this instance on the pointer, which I get as input in the method fs_open.

**Comment by kisvegabor** [comment]
I see. I suggest copy [lv_fs_pc.c](https://github.com/lvgl/lv_fs_if/blob/new-api/lv_fs_pc.c) and modify it with your functions.

**Comment by daowa89** [comment]
I also tried to copy lv_fs_pc.c and implement my modifications. Returning the pointer to the file handle / object is done different to the first version, but I got the same problem. I have absolutely no clue, whats the problem.

**Comment by kisvegabor** [comment]
How does your `fs_open` function look like now?

**Comment by daowa89** [comment]
I managed to run the project without using the interface for the filesystem of lvgl. Thanks for the moment for your support, may I come back to this issue later.

**Comment by beckmx** [comment]
@daowa89 how did you manage to do it?

**Comment by daowa89** [comment]
> @daowa89 how did you manage to do it?

Unfortunately I didnt solve the problem. As long as I dont implement more functions in my application its fine.
