### ISSUE TITLE
Note for Readme.md

### ISSUE THREAD

**Issue by daowa89** [lvgl/lv_fs_if#9]
To enable the file stuff, following functions must be called:
- lv_fs_drv_init
-lv_fs_drv_register

But the most important point is, that before calling lv_fs_drv_register the function lv_init must be called. Otherwise its not possible to register the file functions.

Please add a notice about this in the Readme.md.

**Comment by kisvegabor** [comment]
Thanks, done here: https://github.com/lvgl/lv_fs_if/commit/fdbc24ef429f892616395fee24447342b3acfd32
